### ISSUE TITLE
Use custom domain (maps4html.org)

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/Maps4HTML.github.io#3]
Per https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/49#issuecomment-497965256, the community group currently has a custom domain name, but it currently redirects to the community page on w3.org (https://www.w3.org/community/maps4html/).

Do we want to set up GitHub pages to use the custom domain? (So that it would show https://maps4html.github.io/) It would require setting up a security certificate, which I think is the only hassle.  Also, an agreement to keep the domain alive if we want to use it as the primary URL.

**Comment by prushforth** [comment]
I plan to keep the domain going as long as the project lasts. I guess we can get a cert for free these days. I can check how my registrar would handle this, but I think its a good idea.

**Comment by AmeliaBR** [comment]
I discovered today that setting up a custom domain with Github Pages is easier than I thought: they take care of all the HTTPS certificates! That means that all you need to do is set up the DNS records to point to the GH Pages server.

If decide to use the domain in this way, Peter, the details are here:

- [detailed info on the DNS set up & IP addresses](https://help.github.com/en/articles/setting-up-an-apex-domain)

- [general overview](https://help.github.com/en/articles/quick-start-setting-up-a-custom-domain)

- Once the domain is set up, turn on "enforce HTTPS" [in the settings for this repo](https://github.com/Maps4HTML/Maps4HTML.github.io/settings)

**Comment by prushforth** [comment]
I will try to get to this next week.  Hopefully can direct part of the custom domain traffic to the CG home.

**Comment by prushforth** [comment]
Hmm.  I updated the DNS record from https://www.w3.org/community/maps4html/ to https://maps4html.github.io/ but it's not working.  I understand that DNS changes can take some time to propagate, so I will give it a little time to see if it takes.

**Comment by prushforth** [comment]
> If decide to use the domain in this way, Peter

@AmeliaBR  I found your links to be very helpful, and easy enough to do.  Would be willing to revert for some time if it is going to be an ongoing disruption to you and @NickFitz .  LMK.
